### ISSUE TITLE
Patient- och vårdgivarsidor

### ISSUE THREAD

**Issue by NybergViktor** [johnsson84/HealthCareAB_Backend#8]
Personliga dashboards som visar relevant information som
kommande möten, möteshistorik och personliga profiler.

Profile needs to be done before starting issues listed below.

- [x] Check this if profile is done

- [x] johnsson84/HealthCareAB_Frontend#30
- [x] johnsson84/HealthCareAB_Backend#18
